trigger: none
pr:
  autoCancel: true
  branches:
    include:
      - '*'
stages:
- stage: test
  variables:
    - group: cat
  jobs:
  - job: test
    timeoutInMinutes: 300
    pool:
      vmImage: 'macOS-latest'
    steps:
      - checkout: self
      
      - template: setup.yml
