trigger: none
pr:
  - 'main'
  - 'develop'
stages:
- stage: test
  variables:
    - group: cat
  jobs:
  - job: test
    timeoutInMinutes: 300
    pool:
      vmImage: 'macOS-latest'
    steps:
      - checkout: self
      
      - template: setup.yml
      
      - task: CmdLine@2
        displayName: yarn bundle
        inputs:
          script: yarn bundle
          
