trigger: none
pr:
  - 'main'
  - 'develop'
stages:
- stage: test
  variables:
    - group: cat
  jobs:
  - job: test
    timeoutInMinutes: 300
    pool: Spiria-OSX
    steps:
      - checkout: self
      
      - template: setup.yml
          
