// Copy from Caterpillar Web App: src/common/utils/colour-palettes.ts

import {ColourPaletteItem} from './colors';

export const MATERIAL_COLOUR_PALETTE: ColourPaletteItem[] = [
  {hexCode: '#e6d905', label: 'lemon'},
  {hexCode: '#ffc240', label: 'peach'},
  {hexCode: '#ff7639', label: 'tangerine'},
  {hexCode: '#f63b5a', label: 'guava'},
  {hexCode: '#d110aa', label: 'grape'},
  {hexCode: '#8244cf', label: 'berry'},
  {hexCode: '#447ccf', label: 'mist'},
  {hexCode: '#bcea4f', label: 'lime'},
  {hexCode: '#2adc71', label: 'ocean'},
  {hexCode: '#00b689', label: 'forest'},
  {hexCode: '#bc6738', label: 'earth'},
  {hexCode: '#996e56', label: 'mud'},
];

export const MATERIAL_COLOUR_PALETTE_LEGACY: ColourPaletteItem[] = [
  {hexCode: '#000000', label: '01'},
  {hexCode: '#FF0000', label: '02'},
  {hexCode: '#FFFF00', label: '03'},
  {hexCode: '#00FF00', label: '04'},
  {hexCode: '#00FFFF', label: '05'},
  {hexCode: '#0000FF', label: '06'},
  {hexCode: '#FF00FF', label: '07'},
  {hexCode: '#FFFFFF', label: '08'},
  {hexCode: '#808080', label: '09'},
  {hexCode: '#C0C0C0', label: '10'},
  {hexCode: '#FFBA75', label: '11'},
  {hexCode: '#C6AEC4', label: '12'},
  {hexCode: '#DACA9A', label: '13'},
  {hexCode: '#A7C7CD', label: '14'},
  {hexCode: '#FF8000', label: '15'},
  {hexCode: '#008020', label: '16'},
  {hexCode: '#80FF80', label: '17'},
  {hexCode: '#0000C8', label: '18'},
  {hexCode: '#8080FF', label: '19'},
  {hexCode: '#800020', label: '20'},
  {hexCode: '#FF8080', label: '21'},
  {hexCode: '#804000', label: '22'},
  {hexCode: '#800080', label: '23'},
  {hexCode: '#808040', label: '24'},
  {hexCode: '#C6C600', label: '25'},
  {hexCode: '#FF80C0', label: '26'},
  {hexCode: '#408080', label: '27'},
  {hexCode: '#FF80FF', label: '28'},
  {hexCode: '#800040', label: '29'},
  {hexCode: '#8000FF', label: '30'},
  {hexCode: '#000080', label: '31'},
  {hexCode: '#00C8C8', label: '32'},
];

export const SHIFT_COLOUR_PALETTE: ColourPaletteItem[] = [
  {hexCode: '#e6d905', label: 'colour_lemon'},
  {hexCode: '#ffc240', label: 'colour_peach'},
  {hexCode: '#ff7639', label: 'colour_tangerine'},
  {hexCode: '#f63b5a', label: 'colour_guava'},
  {hexCode: '#d110aa', label: 'colour_grape'},
  {hexCode: '#8244cf', label: 'colour_berry'},
  {hexCode: '#447ccf', label: 'colour_mist'},
  {hexCode: '#bcea4f', label: 'colour_lime'},
  {hexCode: '#2adc71', label: 'colour_ocean'},
  {hexCode: '#00b689', label: 'colour_forest'},
  {hexCode: '#bc6738', label: 'colour_earth'},
  {hexCode: '#996e56', label: 'colour_mud'},
];

export const PERSON_COLOUR_PALETTE: ColourPaletteItem[] = [
  {hexCode: '#e6d905', label: 'colour_lemon', useLightForeground: false},
  {hexCode: '#bcea4f', label: 'colour_lime', useLightForeground: false},
  {hexCode: '#2adc71', label: 'colour_ocean', useLightForeground: false},
  {hexCode: '#00b689', label: 'colour_forest', useLightForeground: true},
  {hexCode: '#447ccf', label: 'colour_mist', useLightForeground: true},
  {hexCode: '#8244cf', label: 'colour_berry', useLightForeground: true},
  {hexCode: '#d110aa', label: 'colour_grape', useLightForeground: true},
  {hexCode: '#f63b5a', label: 'colour_guava', useLightForeground: true},
  {hexCode: '#ff7639', label: 'colour_tangerine', useLightForeground: true},
];
